---
title: "Boston Maps"
output: html_document
---

Here's a Map of all the restaurants in Boston:
```{r, include=FALSE}
library(readr)
library(sf)
library(leaflet)
library(widgetframe)


restaurant_list<-read_csv("D:/R Projects/Boston/Boston Restaurants Updated.csv")
restaurant_list<-restaurant_list[-which(restaurant_list$Longitude %in% NA),]

boston<-st_read("D:/R Projects/Boston/Shapefiles/Boston_Neighborhoods.shp")
boston<-st_transform(boston,"+proj=longlat +datum=WGS84")

labels<-sprintf("%s <br/> %s, %s", restaurant_list$BusinessName, restaurant_list$Address, restaurant_list$CITY)%>%lapply(htmltools::HTML)

resmap<- leaflet(boston)%>%addTiles()%>%setView(lng=-71 ,lat= 42.28,zoom=12)%>%
 addPolygons(fillOpacity=0,weight=2, group="outline")%>%addCircleMarkers(
   lng=restaurant_list$Longitude,lat=restaurant_list$Latitude,color = "#ff0000", radius=1)
```

```{r Boston restaurant map, echo=FALSE, message=FALSE, warning=FALSE}
frameWidget(resmap)
```


Restaurant Count by Neighborhood:
```{r , include= FALSE}
library(readr)
library(sf)
library(sp)
library(leaflet)
library(ggplot2)
library(htmlwidgets)

br<-read_csv("D:/R Projects/Boston/Boston Restaurants Updated.csv")
br<-br[-which(br$Longitude %in% NA),]

boston<-st_read("D:/R Projects/Boston/Shapefiles/Boston_Neighborhoods.shp")
boston<-st_transform(boston,"+proj=longlat +datum=WGS84")

coordinates(br)<-~Longitude+Latitude
boston<-as_Spatial(boston)

proj4string(boston) <- CRS("+proj=longlat +datum=WGS84 +units=m")
proj4string(br) <- CRS("+proj=longlat +datum=WGS84 +units=m")

x<-over(br,boston)
bruh<-as.data.frame(table(x$Name))

z<-ggplot(bruh, aes(x=reorder(bruh$Var1,bruh$Freq),y=bruh$Freq))+
  geom_bar(stat="identity")+coord_flip() + ylab("Neighborhood") + xlab("Restaurant Count")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
z
```


